/**
 * Block Manifest — Central Registry
 *
 * Maps block IDs to metadata, dependencies, and triggers.
 * The assembler reads this to decide which blocks to include.
 */

import type { BlockManifestEntry } from './types';

export const BLOCKS_MANIFEST: BlockManifestEntry[] = [

  // ─── FOUNDATION (always included) ───

  {
    id: 'foundation/package-json',
    name: 'Package Configuration',
    category: 'foundation',
    description: 'package.json with deps aggregated from all selected blocks',
    depends_on: [],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: [],
    produces_files: ['package.json'],
    requires_env: [],
    requires_packages: {
      'next': '15.3.6',
      'react': '^19.0.0',
      'react-dom': '^19.0.0',
      'lucide-react': '^0.468.0',
    },
    requires_dev_packages: {
      '@types/node': '^22.0.0',
      '@types/react': '^19.0.0',
      '@types/react-dom': '^19.0.0',
      'typescript': '^5.7.0',
      'tailwindcss': '^3.4.17',
      'postcss': '^8.5.0',
      'autoprefixer': '^10.4.20',
      'eslint': '^9.17.0',
      'eslint-config-next': '15.3.6',
    },
  },

  {
    id: 'foundation/tsconfig',
    name: 'TypeScript Config',
    category: 'foundation',
    description: 'tsconfig.json for Next.js',
    depends_on: [],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: [],
    produces_files: ['tsconfig.json'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'foundation/tailwind-config',
    name: 'Tailwind Configuration',
    category: 'foundation',
    description: 'tailwind.config.ts with dynamic design_system colors',
    depends_on: [],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: [],
    produces_files: ['tailwind.config.ts'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'foundation/postcss-config',
    name: 'PostCSS Config',
    category: 'foundation',
    description: 'postcss.config.js',
    depends_on: [],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: [],
    produces_files: ['postcss.config.js'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'foundation/next-config',
    name: 'Next.js Config',
    category: 'foundation',
    description: 'next.config.js',
    depends_on: [],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: [],
    produces_files: ['next.config.js'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'foundation/globals-css',
    name: 'Global Styles',
    category: 'foundation',
    description: 'globals.css with Google Fonts and design tokens',
    depends_on: [],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: [],
    produces_files: ['src/app/globals.css'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'foundation/root-layout',
    name: 'Root Layout',
    category: 'foundation',
    description: 'src/app/layout.tsx',
    depends_on: ['foundation/globals-css'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: [],
    produces_files: ['src/app/layout.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'foundation/app-providers',
    name: 'App Providers',
    category: 'foundation',
    description: 'Aggregator: composes React context providers (Toast, Cart, Wishlist) into single wrapper',
    depends_on: ['foundation/root-layout'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: [],
    produces_files: ['src/app/providers.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'foundation/readme',
    name: 'README.md',
    category: 'foundation',
    description: 'Comprehensive README with features, setup, deployment instructions',
    depends_on: [],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: [],
    produces_files: ['README.md'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'foundation/env-example',
    name: 'Environment Example',
    category: 'foundation',
    description: '.env.example aggregated from all blocks + .gitignore',
    depends_on: [],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: [],
    produces_files: ['.env.example', '.gitignore'],
    requires_env: [
      { name: 'NEXT_PUBLIC_APP_URL', example: 'http://localhost:3000', description: 'App base URL' },
    ],
    requires_packages: {},
  },

  // ─── AUTH ───

  {
    id: 'auth/supabase-client',
    name: 'Supabase Client',
    category: 'auth',
    description: 'Browser + Server Supabase clients with SSR cookie handling',
    depends_on: ['foundation/package-json'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: ['auth_required', 'database_required'],
    produces_files: ['src/lib/supabase/client.ts', 'src/lib/supabase/server.ts'],
    requires_env: [
      { name: 'NEXT_PUBLIC_SUPABASE_URL', example: 'https://xxx.supabase.co', description: 'Supabase project URL' },
      { name: 'NEXT_PUBLIC_SUPABASE_ANON_KEY', example: 'eyJ...', description: 'Supabase anon key' },
      { name: 'SUPABASE_SERVICE_ROLE_KEY', example: 'eyJ...', description: 'Supabase service role key (server only)' },
    ],
    requires_packages: {
      '@supabase/supabase-js': '^2.39.0',
      '@supabase/ssr': '^0.1.0',
    },
  },

  {
    id: 'auth/middleware',
    name: 'Auth Middleware',
    category: 'auth',
    description: 'Supabase auth middleware + route protection',
    depends_on: ['auth/supabase-client'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: ['auth_required'],
    produces_files: ['src/lib/supabase/middleware.ts', 'src/middleware.ts'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'auth/login-page',
    name: 'Login Page',
    category: 'auth',
    description: 'Email + Google OAuth login page',
    depends_on: ['auth/supabase-client', 'foundation/globals-css'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: ['auth_required'],
    produces_files: ['src/app/login/page.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'auth/signup-page',
    name: 'Signup Page',
    category: 'auth',
    description: 'Email registration page',
    depends_on: ['auth/supabase-client', 'foundation/globals-css'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: ['auth_required'],
    produces_files: ['src/app/signup/page.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'auth/callback',
    name: 'Auth Callback',
    category: 'auth',
    description: 'OAuth callback route',
    depends_on: ['auth/supabase-client'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: ['auth_required'],
    produces_files: ['src/app/api/auth/callback/route.ts'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'auth/user-hook',
    name: 'User Hook',
    category: 'auth',
    description: 'useUser() hook for client-side auth state',
    depends_on: ['auth/supabase-client', 'database/types'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: ['auth_required'],
    produces_files: ['src/hooks/useUser.ts'],
    requires_env: [],
    requires_packages: {},
  },

  // ─── DATABASE ───

  {
    id: 'database/types',
    name: 'Database Types',
    category: 'database',
    description: 'Supabase database type definitions',
    depends_on: ['auth/supabase-client'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: ['database_required'],
    produces_files: ['src/lib/database.types.ts'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'database/migrations',
    name: 'Database Migrations',
    category: 'database',
    description: 'Supabase SQL migrations',
    depends_on: ['database/types'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: ['database_required'],
    produces_files: ['supabase/migrations/001_initial.sql'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'database/crud-helpers',
    name: 'CRUD Helpers',
    category: 'database',
    description: 'Generic CRUD helper functions for Supabase',
    depends_on: ['auth/supabase-client'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: ['database_required'],
    produces_files: ['src/lib/crud.ts'],
    requires_env: [],
    requires_packages: {},
  },

  // ─── UI ───

  {
    id: 'ui/header',
    name: 'Header',
    category: 'ui',
    description: 'Site header with navigation and auth state',
    depends_on: ['foundation/globals-css'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: [],
    produces_files: ['src/components/Header.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'ui/footer',
    name: 'Footer',
    category: 'ui',
    description: 'Site footer',
    depends_on: ['foundation/globals-css'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: [],
    produces_files: ['src/components/Footer.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'ui/dashboard-nav',
    name: 'Dashboard Navigation',
    category: 'ui',
    description: 'Dashboard top navigation with user menu',
    depends_on: ['foundation/globals-css'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: [],
    produces_files: ['src/components/DashboardNav.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'ui/dashboard-layout',
    name: 'Dashboard Layout',
    category: 'ui',
    description: 'Dashboard layout wrapper',
    depends_on: ['ui/dashboard-nav'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: [],
    produces_files: ['src/app/dashboard/layout.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'ui/loading-states',
    name: 'Loading States',
    category: 'ui',
    description: 'Loading spinners, skeletons, empty states',
    depends_on: ['foundation/globals-css'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: [],
    produces_files: ['src/components/LoadingStates.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'ui/toast',
    name: 'Toast Notifications',
    category: 'ui',
    description: 'Toast notification system',
    depends_on: ['foundation/globals-css'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: [],
    produces_files: ['src/components/Toast.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  // ─── FEATURES ───

  {
    id: 'feature/stripe-setup',
    name: 'Stripe Setup',
    category: 'feature',
    description: 'Stripe client/server config with plan definitions',
    depends_on: ['foundation/package-json'],
    project_types: ['saas'],
    feature_triggers: ['payment', 'subscription', 'billing', 'monetization', 'stripe', 'pricing'],
    tech_triggers: ['apis_needed:stripe'],
    produces_files: ['src/lib/stripe.ts', 'src/lib/stripe-client.ts'],
    requires_env: [
      { name: 'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY', example: 'pk_test_...', description: 'Stripe publishable key' },
      { name: 'STRIPE_SECRET_KEY', example: 'sk_test_...', description: 'Stripe secret key' },
      { name: 'STRIPE_WEBHOOK_SECRET', example: 'whsec_...', description: 'Stripe webhook secret' },
      { name: 'STRIPE_PRO_PRICE_ID', example: 'price_...', description: 'Stripe Pro plan price ID' },
    ],
    requires_packages: {
      '@stripe/stripe-js': '^2.4.0',
      'stripe': '^14.14.0',
    },
  },

  {
    id: 'feature/stripe-checkout',
    name: 'Stripe Checkout',
    category: 'feature',
    description: 'Checkout session API route',
    depends_on: ['feature/stripe-setup', 'auth/supabase-client'],
    project_types: ['saas'],
    feature_triggers: ['payment', 'subscription', 'checkout'],
    tech_triggers: ['apis_needed:stripe'],
    produces_files: ['src/app/api/stripe/checkout/route.ts'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/stripe-webhook',
    name: 'Stripe Webhook',
    category: 'feature',
    description: 'Stripe webhook handler for subscription events',
    depends_on: ['feature/stripe-setup', 'auth/supabase-client'],
    project_types: ['saas'],
    feature_triggers: ['payment', 'subscription', 'webhook'],
    tech_triggers: ['apis_needed:stripe'],
    produces_files: ['src/app/api/stripe/webhook/route.ts'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/stripe-billing-page',
    name: 'Billing Page',
    category: 'feature',
    description: 'Dashboard billing/subscription management page',
    depends_on: ['feature/stripe-setup', 'auth/user-hook', 'ui/dashboard-layout'],
    project_types: ['saas'],
    feature_triggers: ['billing', 'subscription', 'pricing'],
    tech_triggers: ['apis_needed:stripe'],
    produces_files: ['src/app/dashboard/billing/page.tsx', 'src/components/PricingCard.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/usage-tracking',
    name: 'Usage Tracking',
    category: 'feature',
    description: 'API usage counting, rate limiting, usage card component',
    depends_on: ['auth/supabase-client', 'feature/stripe-setup'],
    project_types: ['saas'],
    feature_triggers: ['usage', 'limit', 'rate', 'quota'],
    tech_triggers: ['auth_required'],
    produces_files: ['src/lib/usage.ts', 'src/app/api/usage/route.ts', 'src/components/UsageCard.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/file-upload',
    name: 'File Upload',
    category: 'feature',
    description: 'File upload component with Supabase Storage',
    depends_on: ['auth/supabase-client'],
    project_types: 'all',
    feature_triggers: ['upload', 'file', 'image', 'document', 'attachment'],
    tech_triggers: [],
    produces_files: ['src/components/FileUpload.tsx', 'src/app/api/upload/route.ts'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/search',
    name: 'Search',
    category: 'feature',
    description: 'Search component with debounce and filtering',
    depends_on: ['foundation/globals-css'],
    project_types: 'all',
    feature_triggers: ['search', 'filter', 'find', 'query'],
    tech_triggers: [],
    produces_files: ['src/components/SearchBar.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/email-resend',
    name: 'Email via Resend',
    category: 'feature',
    description: 'Email sending via Resend API',
    depends_on: ['foundation/package-json'],
    project_types: 'all',
    feature_triggers: ['email', 'notification', 'newsletter', 'mail'],
    tech_triggers: ['apis_needed:resend'],
    produces_files: ['src/lib/email.ts', 'src/app/api/send-email/route.ts'],
    requires_env: [
      { name: 'RESEND_API_KEY', example: 're_...', description: 'Resend API key' },
    ],
    requires_packages: {},
  },

  // ─── PAGES ───

  {
    id: 'page/landing',
    name: 'Landing Page',
    category: 'page',
    description: 'Marketing landing page with hero, features, pricing, footer',
    depends_on: ['foundation/globals-css'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: [],
    produces_files: ['src/app/page.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'page/dashboard',
    name: 'Dashboard Page',
    category: 'page',
    description: 'Main user dashboard page',
    depends_on: ['ui/dashboard-layout', 'auth/user-hook', 'api/analyze'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: [],
    produces_files: ['src/app/dashboard/page.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'page/settings',
    name: 'Settings Page',
    category: 'page',
    description: 'User settings/profile page',
    depends_on: ['ui/dashboard-layout', 'auth/user-hook'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: [],
    produces_files: ['src/app/dashboard/settings/page.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'page/admin',
    name: 'Admin Page',
    category: 'page',
    description: 'Admin panel for user/stats management',
    depends_on: ['ui/dashboard-layout', 'auth/supabase-client'],
    project_types: ['saas'],
    feature_triggers: ['admin', 'management', 'moderation'],
    tech_triggers: [],
    produces_files: ['src/app/admin/page.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'page/create',
    name: 'Create Page',
    category: 'page',
    description: 'Dynamic creation form with line items, auto-calculations, and summary panel',
    depends_on: ['ui/dashboard-layout', 'api/analyze'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: [],
    produces_files: ['src/app/dashboard/create/page.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'page/analysis',
    name: 'Analysis Results Page',
    category: 'page',
    description: 'Analysis results display with format-specific renderers (score/report/list/etc.)',
    depends_on: ['ui/dashboard-layout', 'auth/supabase-client', 'api/analyze', 'feature/pdf-export'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: [],
    produces_files: ['src/app/dashboard/analysis/page.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/pdf-export',
    name: 'PDF Export',
    category: 'feature',
    description: 'PDF generation with jsPDF + export buttons component',
    depends_on: ['foundation/package-json'],
    project_types: 'all',
    feature_triggers: ['pdf', 'export', 'download', 'document', 'report', 'invoice', 'plan', 'отчёт', 'скачать'],
    tech_triggers: [],
    produces_files: ['src/lib/pdf-generator.ts', 'src/components/ExportButtons.tsx'],
    requires_env: [],
    requires_packages: {
      'jspdf': '^2.5.1',
    },
  },

  {
    id: 'feature/interactive-wizard',
    name: 'Interactive Wizard',
    category: 'feature',
    description: 'Multi-step wizard/quiz component with progress bar',
    depends_on: ['auth/supabase-client', 'ui/dashboard-layout'],
    project_types: 'all',
    feature_triggers: ['quiz', 'questionnaire', 'wizard', 'survey', 'step-by-step', 'assessment', 'test', 'onboarding', 'опросник', 'тест', 'анкета', 'setup', 'integration', 'connect', 'configure', 'automation', 'workflow', 'guided', 'quick setup', 'configuration'],
    tech_triggers: [],
    produces_files: ['src/components/InteractiveWizard.tsx', 'src/app/dashboard/wizard/page.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/data-charts',
    name: 'Data Charts & Analytics',
    category: 'feature',
    description: 'CSS-only chart components (bar, pie, stat cards) + analytics dashboard',
    depends_on: ['auth/supabase-client', 'ui/dashboard-layout'],
    project_types: 'all',
    feature_triggers: ['chart', 'graph', 'analytics', 'dashboard', 'monitoring', 'tracking', 'visualization', 'statistics', 'график', 'аналитика', 'мониторинг'],
    tech_triggers: [],
    produces_files: ['src/components/ChartComponents.tsx', 'src/app/dashboard/analytics/page.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/csv-processor',
    name: 'CSV Batch Processor',
    category: 'feature',
    description: 'CSV upload + drag-n-drop + batch AI processing + export results',
    depends_on: ['auth/supabase-client', 'ui/dashboard-layout', 'api/analyze'],
    project_types: 'all',
    feature_triggers: ['csv', 'batch', 'bulk', 'import', 'spreadsheet', 'excel', 'mass', 'классификатор', 'массовый'],
    tech_triggers: [],
    produces_files: ['src/components/CsvUploader.tsx', 'src/app/api/batch-analyze/route.ts', 'src/app/dashboard/batch/page.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/ai-chatbot',
    name: 'AI Chatbot',
    category: 'feature',
    description: 'AI chat widget with streaming, document upload for RAG-style knowledge base',
    depends_on: ['auth/supabase-client', 'ui/dashboard-layout'],
    project_types: 'all',
    feature_triggers: ['chat', 'chatbot', 'assistant', 'knowledge', 'faq', 'support', 'help', 'чат', 'ассистент', 'база знаний'],
    tech_triggers: [],
    produces_files: ['src/components/AiChatWidget.tsx', 'src/app/api/chat/route.ts', 'src/app/dashboard/chat/page.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  // ─── EXTENDED FEATURES ───

  {
    id: 'feature/notification-system',
    name: 'Notification System',
    category: 'feature',
    description: 'In-app notification center with real-time updates, mark read/unread, delete',
    depends_on: ['auth/supabase-client'],
    project_types: 'all',
    feature_triggers: ['notification', 'alert', 'bell', 'уведомление', 'оповещение'],
    tech_triggers: [],
    produces_files: ['src/components/NotificationCenter.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/comparison-table',
    name: 'Comparison Table',
    category: 'feature',
    description: 'Side-by-side comparison table with check/cross/value cells',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['comparison', 'compare', 'versus', 'vs', 'side-by-side', 'сравнение'],
    tech_triggers: [],
    produces_files: ['src/components/ComparisonTable.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/activity-timeline',
    name: 'Activity Timeline',
    category: 'feature',
    description: 'Vertical timeline of user activity/events with filters',
    depends_on: ['auth/supabase-client'],
    project_types: 'all',
    feature_triggers: ['timeline', 'activity', 'history', 'log', 'audit', 'хронология', 'история'],
    tech_triggers: [],
    produces_files: ['src/components/ActivityTimeline.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/social-sharing',
    name: 'Social Sharing',
    category: 'feature',
    description: 'Share buttons for Twitter, Facebook, LinkedIn + copy link',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['share', 'social', 'twitter', 'facebook', 'linkedin', 'шеринг', 'поделиться'],
    tech_triggers: [],
    produces_files: ['src/components/SocialShare.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/dark-mode-toggle',
    name: 'Dark Mode Toggle',
    category: 'feature',
    description: 'Theme switcher dark/light with localStorage persistence',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['dark mode', 'theme', 'light mode', 'тёмная тема'],
    tech_triggers: [],
    produces_files: ['src/components/ThemeToggle.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/calendar-scheduler',
    name: 'Calendar & Scheduler',
    category: 'feature',
    description: 'Monthly calendar view with events, date selection, navigation',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['calendar', 'schedule', 'booking', 'appointment', 'event', 'расписание', 'календарь'],
    tech_triggers: [],
    produces_files: ['src/components/CalendarScheduler.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/kanban-board',
    name: 'Kanban Board',
    category: 'feature',
    description: 'Drag-and-drop kanban board with columns, cards, priorities',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['kanban', 'board', 'task', 'project', 'trello', 'задачи', 'доска'],
    tech_triggers: [],
    produces_files: ['src/components/KanbanBoard.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/rich-text-editor',
    name: 'Rich Text Editor',
    category: 'feature',
    description: 'WYSIWYG editor with bold, italic, headings, lists, links, code',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['editor', 'wysiwyg', 'rich text', 'cms', 'редактор'],
    tech_triggers: [],
    produces_files: ['src/components/RichTextEditor.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/voice-input',
    name: 'Voice Input',
    category: 'feature',
    description: 'Speech-to-text voice input using Web Speech API',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['voice', 'speech', 'microphone', 'dictation', 'голос', 'микрофон'],
    tech_triggers: [],
    produces_files: ['src/components/VoiceInput.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/qr-code-generator',
    name: 'QR Code Generator',
    category: 'feature',
    description: 'QR code generator with download and copy',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['qr', 'qr code', 'barcode', 'куар'],
    tech_triggers: [],
    produces_files: ['src/components/QrCodeGenerator.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/referral-system',
    name: 'Referral System',
    category: 'feature',
    description: 'Invite friends referral widget with codes and tracking',
    depends_on: ['auth/supabase-client'],
    project_types: 'all',
    feature_triggers: ['referral', 'invite', 'affiliate', 'реферал', 'приглашение'],
    tech_triggers: [],
    produces_files: ['src/components/ReferralWidget.tsx', 'src/app/api/referral/route.ts'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/api-key-management',
    name: 'API Key Management',
    category: 'feature',
    description: 'API key generation, listing, and deletion for SaaS',
    depends_on: ['auth/supabase-client', 'ui/dashboard-layout'],
    project_types: 'all',
    feature_triggers: ['api key', 'developer', 'sdk', 'integration', 'ключ'],
    tech_triggers: [],
    produces_files: ['src/app/dashboard/api-keys/page.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/webhook-receiver',
    name: 'Webhook Receiver',
    category: 'feature',
    description: 'Incoming webhook endpoint with signature validation',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['webhook', 'incoming', 'hook', 'вебхук'],
    tech_triggers: [],
    produces_files: ['src/app/api/webhooks/incoming/route.ts', 'src/lib/webhook-handler.ts'],
    requires_env: [{ name: 'WEBHOOK_SECRET', example: 'whsec_...', description: 'Webhook signature secret' }],
    requires_packages: {},
  },

  {
    id: 'feature/cron-scheduler',
    name: 'Cron Scheduler',
    category: 'feature',
    description: 'Vercel cron job endpoint for scheduled tasks',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['cron', 'scheduled', 'background', 'periodic', 'автоматический'],
    tech_triggers: [],
    produces_files: ['src/app/api/cron/route.ts'],
    requires_env: [{ name: 'CRON_SECRET', example: 'cron_...', description: 'Cron job auth secret' }],
    requires_packages: {},
  },

  {
    id: 'feature/feedback-collector',
    name: 'Feedback Collector',
    category: 'feature',
    description: 'Floating feedback widget with star rating and categories',
    depends_on: ['auth/supabase-client'],
    project_types: 'all',
    feature_triggers: ['feedback', 'review', 'rating', 'nps', 'отзыв', 'обратная связь'],
    tech_triggers: [],
    produces_files: ['src/components/FeedbackWidget.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/waitlist-prelaunch',
    name: 'Waitlist / Pre-launch',
    category: 'feature',
    description: 'Pre-launch waitlist page with email collection',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['waitlist', 'coming soon', 'prelaunch', 'early access', 'лист ожидания'],
    tech_triggers: [],
    produces_files: ['src/app/waitlist/page.tsx', 'src/app/api/waitlist/route.ts'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/pricing-page',
    name: 'Pricing Page',
    category: 'feature',
    description: 'Standalone pricing page with plan cards and annual toggle',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['pricing', 'plans', 'тарифы', 'цены', 'стоимость'],
    tech_triggers: [],
    produces_files: ['src/app/pricing/page.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/blog-cms',
    name: 'Blog / CMS',
    category: 'feature',
    description: 'Blog listing and post pages from Supabase',
    depends_on: ['auth/supabase-client'],
    project_types: 'all',
    feature_triggers: ['blog', 'article', 'post', 'блог', 'статья'],
    tech_triggers: [],
    produces_files: ['src/app/blog/page.tsx', 'src/app/blog/[slug]/page.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/comments-discussion',
    name: 'Comments / Discussion',
    category: 'feature',
    description: 'Comment section with add/delete, avatars, relative time',
    depends_on: ['auth/supabase-client'],
    project_types: 'all',
    feature_triggers: ['comment', 'discussion', 'reply', 'комментарий', 'обсуждение'],
    tech_triggers: [],
    produces_files: ['src/components/CommentSection.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/multi-workspace',
    name: 'Multi-Workspace',
    category: 'feature',
    description: 'Workspace management with create, invite, switch',
    depends_on: ['auth/supabase-client', 'ui/dashboard-layout'],
    project_types: 'all',
    feature_triggers: ['workspace', 'organization', 'team', 'tenant', 'организация', 'команда'],
    tech_triggers: [],
    produces_files: ['src/app/dashboard/workspace/page.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/multi-language',
    name: 'Multi-Language (i18n)',
    category: 'feature',
    description: 'Internationalization with React context, useT() hook, LanguageSwitcher (EN/DE/RU)',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['i18n', 'language', 'translation', 'multilingual'],
    tech_triggers: [],
    produces_files: ['src/lib/i18n.tsx', 'src/components/LanguageSwitcher.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/image-ai-generator',
    name: 'AI Image Generator',
    category: 'feature',
    description: 'Text-to-image generation via DALL-E with download',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['image generation', 'dall-e', 'ai image', 'генерация изображений'],
    tech_triggers: [],
    produces_files: ['src/components/ImageGenerator.tsx', 'src/app/api/generate-image/route.ts'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/data-export-multi',
    name: 'Multi-Format Export',
    category: 'feature',
    description: 'Export data to JSON, CSV, and TXT formats',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['export', 'download data', 'json export', 'csv export', 'экспорт данных'],
    tech_triggers: [],
    produces_files: ['src/components/DataExportButtons.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/seo-toolkit',
    name: 'SEO Toolkit',
    category: 'feature',
    description: 'Sitemap, robots.txt, and SEO metadata utility',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['seo', 'sitemap', 'meta', 'opengraph', 'robots'],
    tech_triggers: [],
    produces_files: ['src/app/sitemap.ts', 'src/app/robots.ts', 'src/lib/seo.ts'],
    requires_env: [{ name: 'NEXT_PUBLIC_SITE_URL', example: 'https://example.com', description: 'Site URL for SEO' }],
    requires_packages: {},
  },

  {
    id: 'feature/onboarding-tour',
    name: 'Onboarding Tour',
    category: 'feature',
    description: 'Guided step-by-step tour overlay for new users',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['onboarding', 'tour', 'guide', 'walkthrough', 'tutorial', 'обучение'],
    tech_triggers: [],
    produces_files: ['src/components/OnboardingTour.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  // ─── NICHE-SPECIFIC ───

  {
    id: 'feature/health-disclaimer',
    name: 'Health Disclaimer',
    category: 'feature',
    description: 'Medical disclaimer banner/modal/inline for HealthTech',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['health', 'medical', 'disclaimer', 'hipaa', 'здоровье', 'медицина', 'дисклеймер'],
    tech_triggers: [],
    produces_files: ['src/components/HealthDisclaimer.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/health-tracker',
    name: 'Health Tracker',
    category: 'feature',
    description: 'Track health metrics (weight, pressure, sugar, steps) with charts',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['tracker', 'health', 'fitness', 'weight', 'pressure', 'трекер', 'здоровье', 'фитнес'],
    tech_triggers: [],
    produces_files: ['src/components/HealthTracker.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/financial-calculator',
    name: 'Financial Calculator',
    category: 'feature',
    description: 'Loan, ROI, margin, compound interest calculators',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['calculator', 'loan', 'roi', 'margin', 'finance', 'калькулятор', 'кредит', 'маржа'],
    tech_triggers: [],
    produces_files: ['src/components/FinancialCalculator.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/invoice-generator',
    name: 'Invoice Generator',
    category: 'feature',
    description: 'Invoice creation with items, tax, print, HTML download',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['invoice', 'bill', 'receipt', 'счёт', 'квитанция', 'инвойс'],
    tech_triggers: [],
    produces_files: ['src/components/InvoiceGenerator.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/learning-progress',
    name: 'Learning Progress',
    category: 'feature',
    description: 'Course progress tracker with modules, lessons, XP, completion',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['learning', 'course', 'progress', 'lesson', 'module', 'обучение', 'курс', 'прогресс'],
    tech_triggers: [],
    produces_files: ['src/components/LearningProgress.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/certificate-generator',
    name: 'Certificate Generator',
    category: 'feature',
    description: 'Generate course/achievement certificates as PNG via Canvas',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['certificate', 'diploma', 'сертификат', 'диплом'],
    tech_triggers: [],
    produces_files: ['src/components/CertificateGenerator.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  // ─── E-COMMERCE & MEDIA ───

  {
    id: 'feature/product-catalog',
    name: 'Product Catalog',
    category: 'feature',
    description: 'Product catalog with filters, sort, grid/list view, search',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['catalog', 'products', 'shop', 'store', 'каталог', 'товары', 'магазин'],
    tech_triggers: [],
    produces_files: ['src/components/ProductCatalog.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/shopping-cart',
    name: 'Shopping Cart',
    category: 'feature',
    description: 'Cart with add/remove, quantity, slide-over panel, checkout',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['cart', 'shopping', 'checkout', 'корзина', 'покупка'],
    tech_triggers: [],
    produces_files: ['src/components/ShoppingCart.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/wishlist',
    name: 'Wishlist',
    category: 'feature',
    description: 'Wishlist/favorites with toggle button, panel, localStorage',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['wishlist', 'favorites', 'saved', 'избранное', 'закладки'],
    tech_triggers: [],
    produces_files: ['src/components/Wishlist.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/booking-system',
    name: 'Booking System',
    category: 'feature',
    description: 'Date + time slot booking with calendar, form, confirmation',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['booking', 'appointment', 'reservation', 'бронирование', 'запись', 'приём'],
    tech_triggers: [],
    produces_files: ['src/components/BookingSystem.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/image-gallery',
    name: 'Image Gallery',
    category: 'feature',
    description: 'Image grid with lightbox, zoom, navigation, thumbnails',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['gallery', 'photos', 'portfolio', 'галерея', 'фото'],
    tech_triggers: [],
    produces_files: ['src/components/ImageGallery.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/video-player',
    name: 'Video Player',
    category: 'feature',
    description: 'YouTube/Vimeo embed and HTML5 video with thumbnail preview',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['video', 'player', 'youtube', 'vimeo', 'видео'],
    tech_triggers: [],
    produces_files: ['src/components/VideoPlayer.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  // ─── CONTENT & COMMUNICATION ───

  {
    id: 'feature/faq-accordion',
    name: 'FAQ Accordion',
    category: 'feature',
    description: 'FAQ section with search, categories, expandable answers',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['faq', 'questions', 'accordion', 'вопросы', 'чаво'],
    tech_triggers: [],
    produces_files: ['src/components/FaqAccordion.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/testimonials',
    name: 'Testimonials',
    category: 'feature',
    description: 'Customer testimonials carousel or grid with ratings',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['testimonial', 'review', 'отзыв', 'рекомендация'],
    tech_triggers: [],
    produces_files: ['src/components/Testimonials.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/changelog',
    name: 'Changelog',
    category: 'feature',
    description: 'Release notes with version timeline, type filters',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['changelog', 'release', 'version', 'updates', 'обновления'],
    tech_triggers: [],
    produces_files: ['src/components/Changelog.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/file-manager',
    name: 'File Manager',
    category: 'feature',
    description: 'File browser with folders, upload, preview, delete',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['file manager', 'files', 'documents', 'storage', 'файлы', 'документы'],
    tech_triggers: [],
    produces_files: ['src/components/FileManager.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/email-templates',
    name: 'Email Templates',
    category: 'feature',
    description: 'HTML email templates: welcome, reset password, notification, invoice',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['email template', 'welcome email', 'шаблон письма'],
    tech_triggers: [],
    produces_files: ['src/lib/email-templates.ts'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/contact-form',
    name: 'Contact Form',
    category: 'feature',
    description: 'Contact form with validation, API endpoint, success state',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['contact', 'form', 'обратная связь', 'контакт'],
    tech_triggers: [],
    produces_files: ['src/components/ContactForm.tsx', 'src/app/api/contact/route.ts'],
    requires_env: [],
    requires_packages: {},
  },

  // ─── DATA & VISUALIZATION ───

  {
    id: 'feature/in-app-messaging',
    name: 'In-App Messaging',
    category: 'feature',
    description: 'Internal messaging system: conversations, chat, read status',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['messaging', 'inbox', 'direct message', 'сообщения', 'переписка'],
    tech_triggers: [],
    produces_files: ['src/components/InAppMessaging.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/announcement-banner',
    name: 'Announcement Banner',
    category: 'feature',
    description: 'Top banner for announcements, dismissible, localStorage',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['announcement', 'banner', 'notice', 'объявление', 'баннер'],
    tech_triggers: [],
    produces_files: ['src/components/AnnouncementBanner.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/map-location',
    name: 'Map & Location',
    category: 'feature',
    description: 'Interactive map with markers via Leaflet/OpenStreetMap (no API key)',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['map', 'location', 'geo', 'markers', 'карта', 'геолокация'],
    tech_triggers: [],
    produces_files: ['src/components/MapLocation.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/data-table-advanced',
    name: 'Advanced Data Table',
    category: 'feature',
    description: 'Table with sort, search, pagination, bulk actions, selection',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['table', 'data table', 'grid', 'spreadsheet', 'таблица'],
    tech_triggers: [],
    produces_files: ['src/components/DataTableAdvanced.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/tree-view',
    name: 'Tree View',
    category: 'feature',
    description: 'Nested tree with expand/collapse, selection, folder/file icons',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['tree', 'hierarchy', 'nested', 'categories', 'дерево', 'иерархия'],
    tech_triggers: [],
    produces_files: ['src/components/TreeView.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/stats-dashboard',
    name: 'Stats Dashboard',
    category: 'feature',
    description: 'KPI cards with trends, bar chart, period selector',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['stats', 'kpi', 'metrics', 'dashboard stats', 'статистика', 'метрики'],
    tech_triggers: [],
    produces_files: ['src/components/StatsDashboard.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  // ─── ADVANCED AI ───

  {
    id: 'feature/ai-text-to-speech',
    name: 'AI Text-to-Speech',
    category: 'feature',
    description: 'Text-to-speech via OpenAI TTS API with audio player and download',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['tts', 'text to speech', 'voice', 'audio', 'озвучка'],
    tech_triggers: [],
    produces_files: ['src/components/TextToSpeech.tsx', 'src/app/api/text-to-speech/route.ts'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/ai-summarizer',
    name: 'AI Summarizer',
    category: 'feature',
    description: 'Text summarization with style options (brief, bullets, key points)',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['summarize', 'summary', 'tldr', 'суммаризация', 'краткое'],
    tech_triggers: [],
    produces_files: ['src/components/AiSummarizer.tsx', 'src/app/api/summarize/route.ts'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/ai-translator',
    name: 'AI Translator',
    category: 'feature',
    description: 'AI-powered text translation with 12 languages, swap, auto-detect',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['translate', 'translation', 'language', 'перевод', 'переводчик'],
    tech_triggers: [],
    produces_files: ['src/components/AiTranslator.tsx', 'src/app/api/translate/route.ts'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/ai-content-writer',
    name: 'AI Content Writer',
    category: 'feature',
    description: 'AI content generation: blog posts, product descriptions, social posts, emails',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['content writer', 'copywriting', 'generate text', 'копирайтер', 'генерация текста'],
    tech_triggers: [],
    produces_files: ['src/components/AiContentWriter.tsx', 'src/app/api/generate-content/route.ts'],
    requires_env: [],
    requires_packages: {},
  },

  // ─── UX & ENGAGEMENT ───

  {
    id: 'feature/onboarding-checklist',
    name: 'Onboarding Checklist',
    category: 'feature',
    description: 'First-steps checklist with progress bar, dismissible, localStorage',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['checklist', 'getting started', 'first steps', 'чеклист', 'начало работы'],
    tech_triggers: [],
    produces_files: ['src/components/OnboardingChecklist.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/gamification',
    name: 'Gamification',
    category: 'feature',
    description: 'XP, levels, streaks, badges, leaderboard for user engagement',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['gamification', 'badges', 'xp', 'leaderboard', 'achievement', 'геймификация', 'бейджи'],
    tech_triggers: [],
    produces_files: ['src/components/Gamification.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/user-profile-page',
    name: 'User Profile',
    category: 'feature',
    description: 'Public user profile with avatar, bio, stats, activity, editable',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['profile', 'user page', 'avatar', 'профиль', 'аватар'],
    tech_triggers: [],
    produces_files: ['src/components/UserProfile.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'feature/cookie-consent',
    name: 'Cookie Consent',
    category: 'feature',
    description: 'GDPR cookie banner with category toggles and privacy settings',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['cookie', 'gdpr', 'privacy', 'consent', 'куки', 'конфиденциальность'],
    tech_triggers: [],
    produces_files: ['src/components/CookieConsent.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  // ─── API ───

  {
    id: 'api/analyze',
    name: 'AI Analysis Route',
    category: 'api',
    description: 'Main AI analysis API route (OpenAI/Claude)',
    depends_on: ['auth/supabase-client'],
    project_types: 'all',
    feature_triggers: ['analysis', 'ai', 'generate', 'process'],
    tech_triggers: [],
    produces_files: ['src/app/api/analyze/route.ts'],
    requires_env: [
      { name: 'OPENAI_API_KEY', example: 'sk-...', description: 'OpenAI API key' },
      { name: 'OPENAI_MODEL', example: 'gpt-4o-mini', description: 'OpenAI model' },
    ],
    requires_packages: {
      'openai': '4.24.7',
    },
  },

  {
    id: 'api/crud-routes',
    name: 'CRUD API Routes',
    category: 'api',
    description: 'Generic CRUD API routes template',
    depends_on: ['auth/supabase-client'],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: ['database_required'],
    produces_files: ['src/app/api/items/route.ts'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'api/error-handler',
    name: 'Error Handler',
    category: 'api',
    description: 'Centralized API error handling utility',
    depends_on: [],
    project_types: 'all',
    feature_triggers: [],
    tech_triggers: [],
    produces_files: ['src/lib/api-error.ts'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'page/history',
    name: 'History Page',
    category: 'page',
    description: 'History/list page showing all past invoices with search, filter, status management',
    depends_on: ['ui/dashboard-layout'],
    project_types: 'all',
    feature_triggers: ['history', 'archive', 'past', 'list'],
    tech_triggers: [],
    produces_files: ['src/app/dashboard/history/page.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'api/send-email',
    name: 'Send Email API',
    category: 'api',
    description: 'API route for sending emails with PDF attachments via Resend',
    depends_on: [],
    project_types: 'all',
    feature_triggers: ['email', 'send', 'mail', 'notify'],
    tech_triggers: [],
    produces_files: ['src/app/api/send-email/route.ts'],
    requires_env: [
      { name: 'RESEND_API_KEY', example: 're_xxxxxxxxxxxx', description: 'Resend API key for sending emails (optional)' },
      { name: 'EMAIL_FROM', example: 'noreply@yourdomain.com', description: 'From email address (optional)' },
    ],
    requires_packages: {},
  },

  {
    id: 'page/clients',
    name: 'Clients Page',
    category: 'page',
    description: 'Client database with CRUD, search, financial stats per client',
    depends_on: ['ui/dashboard-layout'],
    project_types: 'all',
    feature_triggers: ['client', 'customer', 'contact', 'recipient', 'vendor'],
    tech_triggers: [],
    produces_files: ['src/app/dashboard/clients/page.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'page/reports',
    name: 'Reports Page',
    category: 'page',
    description: 'Financial reports with income/tax/client breakdowns, period filters, CSV export',
    depends_on: ['ui/dashboard-layout'],
    project_types: 'all',
    feature_triggers: ['report', 'analytics', 'revenue', 'income', 'tax'],
    tech_triggers: [],
    produces_files: ['src/app/dashboard/reports/page.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'page/legal',
    name: 'Legal Pages',
    category: 'page',
    description: 'Privacy Policy, Terms of Service, About Us, FAQ pages + admin legal editor with placeholder highlighting',
    depends_on: ['ui/dashboard-layout'],
    project_types: 'all',
    feature_triggers: ['privacy', 'terms', 'legal', 'faq', 'about'],
    tech_triggers: [],
    produces_files: [
      'src/app/privacy/page.tsx',
      'src/app/terms/page.tsx',
      'src/app/about/page.tsx',
      'src/app/faq/page.tsx',
      'src/app/dashboard/legal-editor/page.tsx',
    ],
    requires_env: [],
    requires_packages: {},
  },

  // ─── PROJECT TYPE: SaaS ───

  {
    id: 'project-type/saas-subscription',
    name: 'Subscription Management',
    category: 'project-type',
    description: 'Subscription lifecycle management for SaaS',
    depends_on: ['feature/stripe-setup', 'auth/supabase-client'],
    project_types: ['saas'],
    feature_triggers: ['subscription', 'plan', 'tier'],
    tech_triggers: [],
    produces_files: ['src/lib/subscription.ts'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'project-type/saas-team',
    name: 'Team Management',
    category: 'project-type',
    description: 'Team/organization management for SaaS',
    depends_on: ['auth/supabase-client', 'database/types'],
    project_types: ['saas'],
    feature_triggers: ['team', 'organization', 'invite', 'collaborate'],
    tech_triggers: [],
    produces_files: ['src/app/dashboard/team/page.tsx', 'src/app/api/team/route.ts'],
    requires_env: [],
    requires_packages: {},
  },

  // ─── PROJECT TYPE: Marketplace ───

  {
    id: 'project-type/marketplace-listings',
    name: 'Marketplace Listings',
    category: 'project-type',
    description: 'Listing CRUD, cards, and detail pages',
    depends_on: ['auth/supabase-client', 'database/crud-helpers', 'ui/loading-states'],
    project_types: ['marketplace'],
    feature_triggers: ['listing', 'product', 'catalog', 'marketplace', 'item'],
    tech_triggers: [],
    produces_files: [
      'src/app/listings/page.tsx',
      'src/app/listings/[id]/page.tsx',
      'src/app/listings/new/page.tsx',
      'src/app/api/listings/route.ts',
      'src/components/ListingCard.tsx',
    ],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'project-type/marketplace-reviews',
    name: 'Review System',
    category: 'project-type',
    description: 'Review/rating system for marketplace items',
    depends_on: ['auth/supabase-client', 'project-type/marketplace-listings'],
    project_types: ['marketplace'],
    feature_triggers: ['review', 'rating', 'feedback', 'star'],
    tech_triggers: [],
    produces_files: ['src/components/ReviewForm.tsx', 'src/components/ReviewList.tsx', 'src/app/api/reviews/route.ts'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'project-type/marketplace-messaging',
    name: 'Messaging',
    category: 'project-type',
    description: 'User-to-user messaging system',
    depends_on: ['auth/supabase-client'],
    project_types: ['marketplace'],
    feature_triggers: ['message', 'chat', 'contact', 'inbox'],
    tech_triggers: [],
    produces_files: ['src/app/dashboard/messages/page.tsx', 'src/app/api/messages/route.ts'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'project-type/marketplace-search',
    name: 'Marketplace Search & Filters',
    category: 'project-type',
    description: 'Advanced search with category/price/location filters',
    depends_on: ['auth/supabase-client', 'feature/search'],
    project_types: ['marketplace'],
    feature_triggers: ['search', 'filter', 'category'],
    tech_triggers: [],
    produces_files: ['src/components/MarketplaceFilters.tsx'],
    requires_env: [],
    requires_packages: {},
  },

  // ─── PROJECT TYPE: PWA ───

  {
    id: 'project-type/pwa-manifest',
    name: 'PWA Manifest',
    category: 'project-type',
    description: 'Web app manifest for installable PWA',
    depends_on: ['foundation/next-config'],
    project_types: ['pwa'],
    feature_triggers: ['mobile', 'install', 'offline', 'pwa'],
    tech_triggers: [],
    produces_files: ['public/manifest.json'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'project-type/pwa-service-worker',
    name: 'Service Worker',
    category: 'project-type',
    description: 'Service worker for offline support and caching',
    depends_on: ['project-type/pwa-manifest'],
    project_types: ['pwa'],
    feature_triggers: ['offline', 'cache', 'service-worker'],
    tech_triggers: [],
    produces_files: ['public/sw.js'],
    requires_env: [],
    requires_packages: {},
  },

  {
    id: 'project-type/pwa-offline',
    name: 'Offline Page',
    category: 'project-type',
    description: 'Offline fallback page + install prompt',
    depends_on: ['project-type/pwa-manifest', 'foundation/globals-css'],
    project_types: ['pwa'],
    feature_triggers: ['offline'],
    tech_triggers: [],
    produces_files: ['src/app/offline/page.tsx', 'src/components/InstallPrompt.tsx'],
    requires_env: [],
    requires_packages: {},
  },
];

/** Quick lookup by ID */
export function getBlock(id: string): BlockManifestEntry | undefined {
  return BLOCKS_MANIFEST.find(b => b.id === id);
}

/** Get all blocks for a category */
export function getBlocksByCategory(category: BlockManifestEntry['category']): BlockManifestEntry[] {
  return BLOCKS_MANIFEST.filter(b => b.category === category);
}
